Repository OpenTekHub/cryptobot, pull requests merged in 2024-10, with the labels that each got.

#18 github Greeting
  .github/workflows/greetings.yml
  bot.py
Labels: bug, help wanted, wob24, level2

#19 Create LICENSE
  LICENSE
Labels: documentation, wob24, level1

#29 Enhance Crypto Price Bot Functionality and User Experience
  bot.py
Labels: enhancement

#45 Add Compare Functionality and Quit Option in Cryptocurrency Bot
  bot.py
Labels: level3, gssoc-ext
